-d C:\Users\Administrator\Documents\stopwatch\impl\gwsynthesis\stopwatch.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst C:\Users\Administrator\Documents\stopwatch\src\stopwatch.cst
-cfg C:\Users\Administrator\Documents\stopwatch\impl\pnr\device.cfg
-sdc C:\Users\Administrator\Documents\stopwatch\src\stopwatch.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
